# Copyright 2021 Guillaume Belanger
# See LICENSE file for licensing details.
name: my-blockchain
description: |
  My-blockchain is an educational blockchain project.
summary: |
  My-blockchain is an educational blockchain project.
containers:
  my-blockchain:
    resource: my-blockchain-image

resources:
  my-blockchain-image:
    type: oci-image
    description: OCI image for my-blockchain (gruyaume/my-blockchain:1.0.0)
