apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-blockchain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-blockchain
  template:
    metadata:
      labels:
        app: my-blockchain
    spec:
      containers:
      - name: my-blockchain
        image: gruyaume/my-blockchain:1.0.0
        imagePullPolicy: Always
        env:
        - name: MY_HOSTNAME
          value: "example-blockchain.com"
        volumeMounts:
          - name: vol
            mountPath: /mempool
      - name: my-miner
        image: gruyaume/my-miner:1.0.0
        imagePullPolicy: Always
        env:
        - name: MY_HOSTNAME
          value: "example-blockchain.com"
        volumeMounts:
        - name: vol
          mountPath: /mempool
      volumes:
      - name: mempool
        hostPath:
          path: /mempool
