apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-blockchain
  annotations:
    kubernetes.io/ingress.class: public
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-blockchain
            port:
              number: 80
