apiVersion: v1
kind: Service
metadata:
  name: my-blockchain
spec:
  selector:
    app: my-blockchain
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
